preload = /home/michael/personal/Pictures/wallpaper.jpg

wallpaper = ,/home/michael/personal/Pictures/wallpaper.jpg

#enable splash text rendering over the wallpaper
splash = false 

#fully disable ipc
ipc = off


